sync:
  defaults:
    mode: "two-way-resolved"
    ignore:
      paths:
        - "bin"
        - "log"
        - "tool"
        - ".DS_Store"
        - ".idea"
        - ".tox"
        - ".venv"
      vcs: true
