import = [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]

[window]
startup_mode = "Maximized"
opacity = 0.99
decorations = "buttonless"
option_as_alt = "Both"

[font]
size = 14

[font.normal]
family = "MesloLGM Nerd Font Mono"

[cursor]
[cursor.style]
shape = "Beam"

